import { createFileRoute, Link } from '@tanstack/react-router';
import { ArrowRight, ArrowUpRight } from 'lucide-react';
import { motion } from 'motion/react';
import { Button } from '@/components/ui/button';
import { images } from '@/lib/barber-data';
import { useBooking } from '@/lib/booking-context';
import { ServiceGrid } from '@/components/ServiceGrid';
import { BarberGrid } from '@/components/BarberGrid';
import { SectionHeading } from '@/components/SectionHeading';
export const Route = createFileRoute('/home')({
  head: () => ({ meta: [{ title: 'Início | barberamostre' }, { name: 'description', content: 'Corte que respeita o estilo. Agende corte, degradê e barba pelo WhatsApp.' }, { property: 'og:title', content: 'Início | barberamostre' }, { property: 'og:description', content: 'Corte que respeita o estilo. Agende corte, degradê e barba pelo WhatsApp.' }, { property: 'og:type', content: 'website' }, { name: 'twitter:card', content: 'summary_large_image' }] }), component: Home,
});
const reveal = { initial: { opacity: 0, y: 18 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true }, transition: { duration: .5 } };
function Home() {
  const { start } = useBooking();
  return <><section className="relative flex min-h-[550px] items-center overflow-hidden bg-card md:h-[55vh] md:min-h-[550px] md:max-h-[780px]"><img src={images.hero} alt="Cadeira de barbeiro e interior clássico da barbearia" width={1600} height={1008} className="absolute inset-0 h-full w-full object-cover object-center" /><div className="absolute inset-0 bg-gradient-to-r from-background via-background/85 to-background/20" /><div className="relative mx-auto w-full max-w-7xl px-5 py-20 sm:px-8"><motion.div {...reveal} className="max-w-2xl"><p className="mb-6 flex items-center gap-3 text-xs font-bold uppercase text-secondary"><span className="h-px w-8 bg-secondary"/> O seu estilo começa aqui</p><h1 className="font-display text-5xl font-black leading-[1.04] sm:text-6xl lg:text-7xl">Corte que respeita o estilo.</h1><p className="mt-6 max-w-lg text-base leading-relaxed text-foreground/85 sm:text-lg">Agende seu horário em 1 minuto, sem ficar pendurado no telefone.</p><div className="mt-8 flex flex-wrap gap-3"><Button size="lg" className="h-13 min-h-12 px-7" onClick={() => start()}>Agendar horário <ArrowUpRight /></Button><Button size="lg" variant="outline" className="h-13 min-h-12 border-foreground/60 bg-transparent px-7 text-foreground hover:bg-foreground/10" asChild><Link to="/servicos">Ver serviços <ArrowRight /></Link></Button></div></motion.div></div><div className="absolute bottom-0 left-0 right-0 border-t border-foreground/20"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-3 text-[10px] font-semibold uppercase text-foreground/75 sm:px-8"><span>Corte · Barba · Estilo</span><span className="hidden sm:inline">Feito no detalhe</span></div></div></section>
    <section className="border-b border-border bg-secondary px-5 py-3 text-center text-sm font-bold text-secondary-foreground">Primeira visita ganha 10% off: cupom NOVOCLIENTE</section>
    <section className="mx-auto max-w-7xl px-5 py-20 sm:px-8 md:py-28"><motion.div {...reveal}><SectionHeading label="01 / O que fazemos" title="Serviço bem feito. Sem atalho." description="Do degradê à navalha, cada detalhe conta. Escolha o serviço que combina com você." /></motion.div><ServiceGrid limit={3} /><Button variant="link" className="mt-8 h-12 px-0 text-foreground hover:text-secondary" asChild><Link to="/servicos">Todos os serviços <ArrowRight /></Link></Button></section>
    <section className="border-y border-border bg-card"><div className="mx-auto grid max-w-7xl md:grid-cols-2"><div className="min-h-80 overflow-hidden"><img src={images.tools} alt="Navalha, pincel e ferramentas de barbearia" width={912} height={1104} loading="lazy" className="h-full max-h-[550px] w-full object-cover" /></div><div className="flex flex-col justify-center px-5 py-16 sm:px-12 lg:px-20"><p className="mb-5 text-xs font-bold uppercase text-secondary">O ritual</p><h2 className="max-w-md text-4xl font-black leading-tight sm:text-5xl">Tradição na mão. Precisão no corte.</h2><p className="mt-5 max-w-md text-sm leading-relaxed text-muted-foreground">Máquina, tesoura e navalha no ritmo certo. Você escolhe o estilo, a gente cuida do acabamento.</p><Button className="mt-8 h-12 w-fit px-6" onClick={() => start()}>Agendar horário <ArrowUpRight /></Button></div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-20 sm:px-8 md:py-28"><SectionHeading label="02 / Profissionais" title="Quem cuida do seu visual." description="Escolha seu profissional e confira os horários disponíveis para consulta." /><BarberGrid /></section>
    <section className="border-t border-border bg-card"><div className="mx-auto max-w-7xl px-5 py-20 sm:px-8"><SectionHeading label="03 / Galeria" title="O resultado está no detalhe." /><div className="grid gap-4 sm:grid-cols-2"><Link to="/galeria" className="group relative overflow-hidden"><img src={images.cut} alt="Degradê com acabamento preciso" width={912} height={1104} loading="lazy" className="aspect-[4/3] w-full object-cover transition-transform duration-500 group-hover:scale-105" /><span className="absolute bottom-0 left-0 right-0 bg-gradient-to-t from-background to-transparent p-5 pt-14 text-lg font-bold">Degradê <ArrowUpRight className="inline size-5" /></span></Link><Link to="/galeria" className="group relative overflow-hidden"><img src={images.beard} alt="Barba alinhada na navalha" width={912} height={1104} loading="lazy" className="aspect-[4/3] w-full object-cover transition-transform duration-500 group-hover:scale-105" /><span className="absolute bottom-0 left-0 right-0 bg-gradient-to-t from-background to-transparent p-5 pt-14 text-lg font-bold">Barba na navalha <ArrowUpRight className="inline size-5" /></span></Link></div><Button variant="link" asChild className="mt-6 h-12 px-0 text-foreground hover:text-secondary"><Link to="/galeria">Ver galeria <ArrowRight /></Link></Button></div></section>
    <section className="border-t border-border bg-card"><div className="mx-auto grid max-w-7xl gap-8 px-5 py-16 sm:px-8 md:grid-cols-[1fr_auto] md:items-center"><div><p className="mb-3 text-xs font-bold uppercase text-secondary">Seu próximo corte</p><h2 className="text-4xl font-black sm:text-5xl">A cadeira está te esperando.</h2></div><Button className="h-12 px-7" onClick={() => start()}>Agendar horário <ArrowUpRight /></Button></div></section></>;
}
